### ISSUE TITLE
As a user who doesn´t remember their password, I want to be able to recover my account

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#1]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Validate new password is valid
   - [ ] Button to resend email
   - [ ] Communication with backend
   - [ ] Show error
   - [ ] Navigate if correct
- [ ] Backend
   - [x] Send SMS
   - [x] Validate fields
   - [ ] Ok if the new password is valid and different
   - [x] Bad if the password is not correct

**Tests**
- [ ] Frontend
   - [ ] Validate password
   - [ ] Show error correctly
   - [ ] Navigate if correct
- [ ] Backend
   - [ ] Invalid password or repeated Bad code
   - [ ] Valid password Ok code
   - [ ] Check if changed if valid
   - [ ] Check if not changed when Bad
