### ISSUE TITLE
As a user, I want select the difficulty of a test

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#10]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Communication with backend
   - [ ] Show error
   - [ ] Navigation
- [ ] Backend
   - [ ] Send test
   - [ ] Validate difficulty

**Tests**
- [ ] Frontend
   - [ ] Validate button is only pressed when difficulty selected
   - [ ] Show error when bad request
   - [ ] Navigate correctly
- [ ] Backend
   - [ ] Send correct test
   - [ ] Validate difficulty
