### ISSUE TITLE
As a user, I want to review a test done in the past

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#11]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Button to go to the questions
   - [ ] Navigation
   - [ ] Communication
   - [ ] Show error
- [ ] Backend
   - [ ] Send results
**Tests**
- [ ] Frontend
   - [ ] Validate the user cannot send new responses and change them
   - [ ] Validate the user can see the result of every question
- [ ] Backend
   - [ ] Send correct test
   - [ ] Validate a user cannot see other's tests
   - [ ] Validate if the user asks for a test that does not exist
