### ISSUE TITLE
As a user, I want to select the interval of time of my stats

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#13]
**Tasks**

- [ ] Frontend
   - [ ] Component to select interval
   - [ ] Communication
   - [ ] Error
- [ ] Backend
    - [ ] Send allowed intervals

**Tests**
- [ ] Frontend
   - [ ] Validate max min interval
 - [ ] Backend
    - [ ] Send correct interval
