### ISSUE TITLE
As a user, I want to review my stats

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#14]
**Tasks**

- [ ] Frontend
   - [ ] Diagrams
      - [ ] Success rate
          - [ ] Filter by difficulty
       - [ ] Words learnt
       - [ ] Days in which the user has used the app
       - [ ] New words
       - [ ] Time
    - [ ] Communication
    - [ ] Error  

**Tests**
- [ ] Frontend
   - [ ] Validate diagrams
   - [ ] Validate filtering
- [ ] Backend
   - [ ]  Send correct stats
