### ISSUE TITLE
As a user, I want to delete the history of tests

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#15]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Error
   - [ ] Ask if sure
- [ ] Backend
   - [ ] Ok and delete
   - [ ] Error if something happened

**Tests**
- [ ] Frontend
   - [ ] If the user does not check sure the request is not sent
   - [ ] If the user checks sure the request is sent
- [ ] Backend
   - [ ] The data has been successfully deleted
