### ISSUE TITLE
As a user, I want to change my password

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#2]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Validate new password is valid
   - [ ] Communication with backend
   - [ ] Show error/Correct
- [x] Backend
   - [x] Validate fields
   - [ ] Ok if the new password is valid and different
   - [x] Bad if the password is not correct

**Tests**
- [ ] Frontend
   - [ ] Validate password
   - [ ] Show error correctly
   - [ ] Navigate if correct
- [ ] Backend
   - [ ] Invalid password or repeated Bad code
   - [ ] Valid password Ok code
   - [ ] Check if changed if valid
   - [ ] Check if not changed when Bad
