### ISSUE TITLE
As a user, I want to delete my account

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#3]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Validate fields
   - [ ] Ask if sure
   - [ ] Communication with backend
   - [ ] Show error
   - [ ] Navigate if correct
- [x] Backend
   - [x] Validate fields
   - [x] Ok if the credentials are correct
   - [x] Bad if the credentials are incorrect
   - [x] Bad if the fields are not correct

**Tests**
- [ ] Frontend
   - [ ] Validate fields
      - [ ] Validate mail
      - [ ] Validate password
   - [ ] Show error correctly
   - [ ] Navigate if correct
   - [ ] Show alert if fields are correct
- [ ] Backend
   - [ ] Invalid fields should send Bad code
   - [ ] Invalid credentials should send Bad code
   - [ ] Valid credentials should send Ok code
   - [ ] If valid the user is deleted
   - [ ] If invalid the user exists yet
