### ISSUE TITLE
As a non signer, I want to register in the app to learn ASL

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#4]
**Tasks**

- [x] Frontend
   - [x] Screen
   - [x] Validate fields
   - [x] Communication with backend
   - [x] Show error
   - [x] Navigate if correct
- [x] Backend
   - [x] Validate fields
   - [x] Ok if the user does not exist and the fields are correct
   - [x] Bad if the user already exists
   - [x] Bad if the fields are not correct

**Tests**
- [ ] Frontend
   - [ ] Validate fields
   - [ ] Show error correctly
   - [ ] Navigate if correct
- [x] Backend
   - [x] Invalid fields should send Bad code
   - [x] Non-existing user and valid fields should send Ok code
   - [x] Existing user should send Bad code
   - [x] If valid the user is added to the DB
   - [x] If invalid the user does not exist in the DB
