### ISSUE TITLE
As a user, I want to login in the app

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#5]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Validate fields
   - [ ] Communication with backend
   - [ ] Show error
   - [ ] Navigate if correct
- [x] Backend
   - [x] Validate fields
   - [x] Ok if the credentials are correct
   - [x] Bad if the credentials are incorrect
   - [x] Bad if the fields are not correct

**Tests**
- [ ] Frontend
   - [ ] Validate fields
      - [ ] Validate mail
      - [ ] Validate password
   - [ ] Show error correctly
   - [ ] Navigate if correct
- [ ] Backend
   - [ ] Invalid fields should send Bad code
   - [ ] Valid credentials should send Ok code
   - [ ] Non existing user should send Bad code
   - [ ] Non valid credentials should send Bad code
