### ISSUE TITLE
As a user, I want to know my result in the test and review it

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#6]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Button to go to the questions
   - [ ] Navigation

**Tests**
- [ ] Frontend
   - [ ] Validate the user cannot send new responses and change them
   - [ ] Validate the user can see the result of every question
