### ISSUE TITLE
As a user, I want to customize the number of questions of a test

### ISSUE THREAD

**Issue by JesusGonzalezA** [JesusGonzalezA/LearnASL#7]
**Tasks**

- [ ] Frontend
   - [ ] Screen
   - [ ] Communication with backend
   - [ ] Show error
   - [ ] Navigation
- [ ] Backend
   - [ ] Send test
   - [ ] Validate number of questions

**Tests**
- [ ] Frontend
   - [ ] Validate limits
   - [ ] Show error when bad request
   - [ ] Navigate correctly
- [ ] Backend
   - [ ] Send correct test
   - [ ] Validate number of questions
